### PR TITLE
Go Modules support

### LINKED ISSUE #65: Go Modules Support
Right now I can technically use this library with projects using go modules, but because it doesn't have a go module initialized, we see:
```
github.com/graph-gophers/dataloader v5.0.0+incompatible
```
I'm not sure if all the semver / module guarantees are properly respected for non-module-based projects.
Could I add go.mod / go.sum files to the repo? Happy to open a PR. 
I could also fork the repo and keep them in my fork if you prefer.

### PR DESCRIPTION
**Pull request by jpastoor**
Here my take on the changes that might be needed to switch to Go Modules using semver.

Fixes #65

### CODE REVIEW

**Comment by AttilaTheFun** [comment]
Thanks for putting this up Joost! @tonyghita I'd love to see this land if you're open to it :)

**Comment by tonyghita** [comment]
Thanks for the contribution and your patience, circling back to this now.

**Comment by tonyghita** [comment]
I've opened #67 in favor of this change, as I've added a few more edits to the change.

**Comment by tonyghita** [comment]
Merged as #67, thank you @jpastoor!

**Pull request closed without merging**
